import 'dotenv/config';
import pg from 'pg';

// Obtain pg client
const client = new pg.Client({
    connectionString: process.env.DATABASE_URL,
    database: 'postgres',
});
// Connect
await client.connect();

// -----------------------------

const dbsSQL = `
SELECT datname FROM pg_database WHERE datistemplate = false;`;

const tblsSQL = `
SELECT table_schema, table_name
FROM information_schema.tables
WHERE table_type = 'BASE TABLE' AND table_schema NOT IN ('pg_catalog', 'information_schema');`;

const usersSql1 = `
CREATE TABLE public.users (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT
);`;

const usersSql2 = `
DROP TABLE public.users CASCADE;
`;

const usersSql3 = `
INSERT INTO public.users (name)
SELECT name
FROM (VALUES
    (1, 'Foo'),
    (2, 'Bar'),
    (3, 'Baz')
) AS v(row_index, name)
RETURNING id, name, v.row_index; 
`;

let sql = `
DELETE FROM public.users AS u
USING (
    SELECT u2.id
    FROM public.users AS u2
    
) as u2 WHERE u.id = u2.id`;

sql = `DROP TABLE IF EXISTS public.people CASCADE;`;
console.log('________________________', (await client.query(sql)).rows);

process.exit();