 
/**
 * @imports
 */
import pg from 'pg';
import { expect } from 'chai';
import SQLClient from '../src/api/sql/SQLClient.js';
import CreateTable from '../src/query/create/CreateTable.js';
import AlterTable from '../src/query/alter/AlterTable.js';
import Parser from '../src/query/Parser.js';

// --------------------------
const pgClient = new pg.Client({
    host: 'localhost',
    port: 5432,
});
await pgClient.connect();
let $pgClient = { query(sql, ...args) {
    //console.log(`\n\n\n\nSQL:`, sql);
    return pgClient.query(sql, ...args);
} };
const sqlClient = new SQLClient($pgClient, { dialect: 'postgres' });
console.log('\n\n\n\n\nn\n\n;;;;;;;;;;;;;;;;;;;;;;;;', await sqlClient.searchPath(), '\n\n\n\n\n');
// --------------------------

describe(`Postgres Create Table & Alter Table statements`, function() {

    describe(`Create Table`, function() {

        it(`DO: Parses a Create Table statement`, async function() {
            const createTableSql = `
            CREATE TABLE IF NOT EXISTS public."te ""st0" (
                id int PRIMARY    KEY CONSTRAINT genn generated by default as identity default geer(11) check (kkd(dkdk)),
                "$ref" int CONSTRAINT nn not    null CONSTRAINT uni_q unique CONSTRAINT fk REFERENCES pretest (id) MATCH FULL ON DELETE RESTRICT ON UPDATE SET NULL,
                ref2 int,
                rand VARCHAR (11) CHECK (rand IS NOT NULL),
                rand2 text,
                CONSTRAINT ck CHECK (ref > 10),
                CONSTRAINT "fk .. "" .. 2" FOREIGN    KEY (ref2) REFERENCES pretest2 (id),
                UNIQUE (rand2,rand)
            )`;
            const tblCreateInstance1 = await Parser.parse({ name: 'some_database' }, createTableSql);
            const tblCreateInstance2 = CreateTable.fromJson(tblCreateInstance1.CONTEXT, tblCreateInstance1.toJson());
            const sql1 = tblCreateInstance1 + '';
            const sql2 = tblCreateInstance2 + '';
            console.log(sql1);
            /*
            console.log(sql2);
            console.log(JSON.stringify(tblCreateInstance1.toJson(), null, 3));
            console.log(JSON.stringify(tblCreateInstance2.toJson(), null, 3));
            */
            expect(sql1).to.eq(sql2);
        });
    });

    describe(`Alter Table`, function() {

        it(`DO: Parses an Alter Table statement`, async function() {
            const alterTableSql = `
            ALTER TABLE IF EXISTS public.test
                RENAME AS "new_tbl_n """"$ ame",
                SET SCHEMA "newDDDDD Dbbbbbb",
                RENAME constraint "constrai_ _nt_name1" TO new_constraint_name,

                ADD constraint constraint_name2 PRIMARY KEY (col_name1),
                ADD constraint fruit_type UNIQUE (hhh),
                ADD PRIMARY KEY (col_name2),
                ADD CHECK (check_expr),

                ADD FULLTEXT INDEX (ft_name),

                ADD column new_col varchar(10) references distant_tbl (id) on update restrict on delete cascade FIRST,
                ADD column new_col2 int AFTER refColumn,

                DROP constraint if    exists constraint_name3 cascade,
                DROP PRIMARY KEY,
                DROP FOREIGN KEY "fk_ $ name",
                DROP COLUMN if exists col_name,
                DROP col_name,

                ALTER column "column _name" set data type varchar(60),
                ALTER constraint constraint_name4 INVISIBLE,
                ALTER COLUMN column_name8 SET COMPRESSION compression_method,
                ALTER constraint constraint_name8 DEFERRABLE
            `;
            const tblAlterInstance1 = await Parser.parse({ name: 'some_database' }, alterTableSql);
            const tblAlterInstance2 = AlterTable.fromJson(tblAlterInstance1.CONTEXT, tblAlterInstance1.toJson());
            const sql1 = tblAlterInstance1 + '';
            const sql2 = tblAlterInstance2 + '';
            console.log(sql1);
            /*
            console.log(sql2);
            console.log(JSON.stringify(tblAlterInstance1.toJson(), null, 3));
            console.log(JSON.stringify(tblAlterInstance2.toJson(), null, 3));
            */
            expect(sql1).to.eq(sql2);
        });
        
        it(`DO: Diffs 2 schemas into an Alter Table statement`, async function() {
            const schemaA = {
                name: 'testt',
                basename: 'public',
                columns: [
                    { name: 'id', type: { name: 'VARCHAR', maxLen: 30 }, default: 20 },
                    { name: 'author', type: { name: 'INT' }, references: { constraintName: 'fkk', table: 'table1', columns: ['col3', 'col4']} },
                ],
                constraints: [
                    { type: 'FOREIGN_KEY', columns: ['col1', 'col2'], references: { table: 'table1', columns: ['col3', 'col4']} },
                    { type: 'PRIMARY_KEY', columns: 'col5' },
                ],
                indexes: []
            };
            const schemaB = {
                name: 'testt',
                basename: 'public2',
                columns: [
                    { name: 'id3', $name: 'id', notNull: true, type: { name: 'vARCHAR', maxLen: 70 }, default: 20 },
                    { name: 'author', type: { name: 'INT' }, references: { constraintName: 'fkk222', $constraintName: 'fkk', table: 'table1', columns: ['col3', 'col5']} },
                ],
                constraints: [
                    { type: 'FOREIGN_KEY', columns: ['col1', 'col2'], references: { table: 'table1', columns: ['col3', 'col4']} },
                    { type: 'PRIMARY_KEY', columns: 'col5' },
                ],
                indexes: []
            };
            const tblAlterInstance1 = AlterTable.fromDiffing({}, schemaA, schemaB);
            const tblAlterInstance2 = AlterTable.fromJson(tblAlterInstance1.CONTEXT, tblAlterInstance1.toJson());
            const sql1 = tblAlterInstance1 + '';
            const sql2 = tblAlterInstance2 + '';
            /*
            console.log(sql1);
            console.log(sql2);
            console.log(JSON.stringify(tblAlterInstance1.toJson(), null, 3));
            console.log(JSON.stringify(tblAlterInstance2.toJson(), null, 3));
            */
            expect(sql1).to.eq(sql2);
        });
            
    });

});
